name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet: [ '2.2.108', '3.0.0' ]
    name: Dotnet ${{ matrix.dotnet }} sample

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Unit Tests
      run: dotnet test
    - name: Update AssemblyInfo files
      uses: docker://gittools/gitversion:5.0.0-latest-linux-netcoreapp2.2
      with:
        args: '-updateassemblyinfo -nocache -output buildserver'
