name: Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Update AssemblyInfo files
      uses: docker://gittools/gitversion:5.0.2-linux
      with:
        args: '-mode ContinuousDelivery -updateassemblyinfo -nocache -output buildserver'
